### ISSUE TITLE
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by Cmahjong** [dji-sdk/Mobile-SDK-Android-V5#1]
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1902)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2673)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2603)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1247)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1322)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:172)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:82)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
        at co_a.co_c.co_a.co_a.co_a.co_b.co_b.co_b(AnalyticsDao_Impl.java:3)
        at co_a.co_c.co_a.co_a.co_a.co_a.co_f(AnalyticsDatabaseController.java:2)
        at co_a.co_c.co_a.co_a.co_a.co_a.co_a(AnalyticsDatabaseController.java:10)
        at co_a.co_c.co_a.co_a.co_b.co_a.init(AnalyticsEngine.java:8)
        at dji.v5.manager.SDKManager.init(SDKManager.java:7)
        at com.silver.drone.common.BaseMainActivityVm.registerApp(BaseMainActivityVm.kt:25)
        at com.silver.drone.MainActivity.startSDKRegistration(MainActivity.kt:158)
        at com.silver.drone.MainActivity.initDrone(MainActivity.kt:150)
        at com.silver.drone.MainActivity.initViewModel(MainActivity.kt:119)
        at com.silver.drone.MainActivity.initView(MainActivity.kt:104)
        at com.silver.base.BaseActivity.onCreate(BaseActivity.kt:37)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3464)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7700) 
gradle 

//大疆
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'androidx.room:room-runtime:2.4.2'
    implementation 'com.commonsware.cwac:saferoom.x:1.3.0'
    implementation 'androidx.room:room-rxjava2:2.4.2'
    implementation 'org.java-websocket:Java-WebSocket:1.5.1'
    kapt  'androidx.room:room-compiler:2.4.2'
    implementation "com.dji:library-networkrtk-helper:2.0.2"
    compileOnly files('libs/aircraft-provided-5.0.0_beta1_322.jar')
    implementation files('libs/aircraft-release-5.0.0_beta1_322_sec.aar')
    runtimeOnly files('libs/networkImp-release-5.0.0_beta1_322.aar')

**Comment by DanLongChen** [comment]
May I ask what Android device you are using when this problem occurs? Have you used our sdk sample?

**Comment by Cmahjong** [comment]
yes , Android device,look your sdk sample impoded 5.0.0_beta1,then occurs this problem

**Comment by DJI-William** [comment]
We cannot reproduce your issue. Coud you please 
1. Try the current Sample. We have updated it already.
2. Please tell use your Android device model and version.

**Comment by eric-dk** [comment]
Steps-to-reproduce:
1. Set up empty project that successfully registers [DJI V4 MSDK](https://github.com/dji-sdk/Mobile-SDK-Android)
1. Launch app onto any Android device
1. Upgrade said project to [DJI V5 MSDK](https://github.com/dji-sdk/Mobile-SDK-Android-V5)
1. Launch app onto said Android device without uninstalling first

Expected:
- App launches and successfully registers DJI V5 MSDK

Actual:
- Registration failure due to the above exception

Workaround:

Call the following *before* registering DJI V5 MSDK:
```java
context.deleteDatabase("DJIAnalytics.db")
```
I suspect there has been a schema change in the analytics database between V4 and V5.

**Comment by DJI-William** [comment]
> Steps-to-reproduce:
> 
> 1. Set up empty project that successfully registers [DJI V4 MSDK](https://github.com/dji-sdk/Mobile-SDK-Android)
> 2. Launch app onto any Android device
> 3. Upgrade said project to [DJI V5 MSDK](https://github.com/dji-sdk/Mobile-SDK-Android-V5)
> 4. Launch app onto said Android device without uninstalling first
> 
> Expected:
> 
> * App launches and successfully registers DJI V5 MSDK
> 
> Actual:
> 
> * Registration failure due to the above exception
> 
> Workaround:
> 
> Call the following _before_ registering DJI V5 MSDK:
> 
> ```java
> context.deleteDatabase("DJIAnalytics.db")
> ```
> 
> I suspect there has been a schema change in the analytics database between V4 and V5.

Much appreciated, I will infor mthe dev team about this issue.

**Comment by DJI-William** [comment]
@Cmahjong and @eric-dk , we have fixed this issue, wait until 5.1 release.
