### ISSUE TITLE
Missing native method isSDKActivated on Motorola G8 Play (ARMv7)

### ISSUE THREAD

**Issue by Padreco-lbr** [dji-sdk/Mobile-SDK-Android-V5#206]
Are you dropping support for armv7 mobiles or are there plans to support it in the future?

SDK Version: 5.8.0-a2
Android: 10 (API Level 29)
Processor arch: ARMv7, Instruction sets: armeabi-v7a, armeabi

Error is the following, during sdk initialization:

FATAL EXCEPTION: DJIExecutor Urgent #1
                                                                             Process: com.panoramaid.flyid, PID: 29737
                                                                             java.lang.UnsatisfiedLinkError: No implementation found for boolean dji.v5.common.register.SDKRelativeJNI.native_isSDKActivated() (tried Java_dji_v5_common_register_SDKRelativeJNI_native_1isSDKActivated and Java_dji_v5_common_register_SDKRelativeJNI_native_1isSDKActivated__)
                                                                             	at dji.v5.common.register.SDKRelativeJNI.native_isSDKActivated(Native Method)
                                                                             	at dji.v5.inner.register.RegistrationManager.co_a(RegistrationManager.java:31)
                                                                             	at dji.v5.manager.SDKManager.co_c(SDKManager.java:13)
                                                                             	at dji.v5.manager.SDKManager.access$lambda$2(Unknown Source:0)
                                                                             	at dji.v5.manager.SDKManager$$Lambda$3.run(Unknown Source:2)

**Comment by dji-lyt** [comment]
Currently, we do not have any plans to support armv7 devices. However, we do support arm64-v8a devices. Would it be possible for you to update to an armv8 device?

**Comment by tiomurray** [comment]
> Currently, we do not have any plans to support armv7 devices. However, we do support arm64-v8a devices. Would it be possible for you to update to an armv8 device?

I have a API 28 device which is not arm64-v8a, so its impossible to run MSDK-V5 in this device? Its possible to run MSDK-V4 on armv7 devices tho?
