### ISSUE TITLE
Didn't find class "dji.v5.manager.interfaces.SDKManagerCallback"

### ISSUE THREAD

**Issue by HadrienBd** [dji-sdk/Mobile-SDK-Android-V5#258]
Hello, I'm trying to add the SDK to a new project following the tutorial : https://developer.dji.com/doc/mobile-sdk-tutorial/en/quick-start/user-project-caution.html.
The project build successfully but the app keeps crashing with the following runtime error.

I'm running the project on a POCO F3 with Android 13.

Here's the error :

```
FATAL EXCEPTION: main
Process: com.alta_ares.myapplication, PID: 31546
java.lang.NoClassDefFoundError: Failed resolution of: Ldji/v5/manager/interfaces/SDKManagerCallback;
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
at android.app.Instrumentation.newApplication(Instrumentation.java:1244)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1485)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1422)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7052)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8261)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.v5.manager.interfaces.SDKManagerCallback" on path: DexPathList[[zip file "/data/app/~~3EFof6WZS3MzS-rBFErRBQ==/com.alta_ares.myapplication-x4eplg3uKSfrRrbrkJmHTg==/base.apk"],nativeLibraryDirectories=[/data/app/~~3EFof6WZS3MzS-rBFErRBQ==/com.alta_ares.myapplication-x4eplg3uKSfrRrbrkJmHTg==/lib/arm64, /data/app/~~3EFof6WZS3MzS-rBFErRBQ==/com.alta_ares.myapplication-x4eplg3uKSfrRrbrkJmHTg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at java.lang.Class.newInstance(Native Method) 
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 
at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52) 
at android.app.Instrumentation.newApplication(Instrumentation.java:1244) 
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1485) 
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1422) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7052) 
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:210) 
at android.os.Looper.loop(Looper.java:299) 
at android.app.ActivityThread.main(ActivityThread.java:8261) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
```

Here's my project gradle : 

```
  apply from:rootProject.file('dependencies.gradle')
  
  buildscript {
      repositories {
          google()
          mavenCentral()
      }
      dependencies {
          // Suggested Android Gradle Plugin Version
          classpath "com.android.tools.build:gradle:7.4.2"
  
          //Suggested Kotlin version
          classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21"
          // ... (remaining code)
      }
  }
```

My app gradle : 

```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.alta_ares.myapplication'
    compileSdk 33

    defaultConfig {
        applicationId "com.alta_ares.myapplication"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a' // MSDK only supports arm64-v8a architecture
        }

        // MSDK related so library
        packagingOptions {
            pickFirst 'lib/arm64-v8a/libc++_shared.so'
            pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        }

        // MSDK related so library
        packagingOptions {
            doNotStrip "*/*/libconstants.so"
            doNotStrip "*/*/libdji_innertools.so"
            doNotStrip "*/*/libdjibase.so"
            doNotStrip "*/*/libDJICSDKCommon.so"
            doNotStrip "*/*/libDJIFlySafeCore-CSDK.so"
            doNotStrip "*/*/libdjifs_jni-CSDK.so"
            doNotStrip "*/*/libDJIRegister.so"
            doNotStrip "*/*/libdjisdk_jni.so"
            doNotStrip "*/*/libDJIUpgradeCore.so"
            doNotStrip "*/*/libDJIUpgradeJNI.so"
            doNotStrip "*/*/libDJIWaypointV2Core-CSDK.so"
            doNotStrip "*/*/libdjiwpv2-CSDK.so"
            doNotStrip "*/*/libFlightRecordEngine.so"
            doNotStrip "*/*/libvideo-framing.so"
            doNotStrip "*/*/libwaes.so"
            doNotStrip "*/*/libagora-rtsa-sdk.so"
            doNotStrip "*/*/libc++.so"
            doNotStrip "*/*/libc++_shared.so"
            doNotStrip "*/*/libmrtc_28181.so"
            doNotStrip "*/*/libmrtc_agora.so"
            doNotStrip "*/*/libmrtc_core.so"
            doNotStrip "*/*/libmrtc_core_jni.so"
            doNotStrip "*/*/libmrtc_data.so"
            doNotStrip "*/*/libmrtc_log.so"
            doNotStrip "*/*/libmrtc_onvif.so"
            doNotStrip "*/*/libmrtc_rtmp.so"
            doNotStrip "*/*/libmrtc_rtsp.so"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.dji:dji-sdk-v5-aircraft:5.2.0'
    compileOnly 'com.dji:dji-sdk-v5-aircraft-provided:5.2.0'
    runtimeOnly 'com.dji:dji-sdk-v5-networkImp:5.2.0'
}

```
And the uxsdk gradle : 

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    resourcePrefix "uxsdk_"
    defaultConfig {
        minSdkVersion Integer.parseInt(project.ANDROID_MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(project.ANDROID_TARGET_SDK_VERSION)
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions{
        jvmTarget = JavaVersion.VERSION_1_8
        freeCompilerArgs += ["-Xjvm-default=all"]
    }
}

dependencies {
    implementation deps.annotation
    implementation deps.appcompat
    implementation deps.multidex
    implementation deps.legacySupport
    implementation deps.recyclerview
    implementation deps.okio
    implementation deps.wire
    implementation deps.constraintLayout
    implementation deps.lifecycleJava8
    implementation deps.lifecycleRuntime
    implementation deps.lifecycleProcess
    implementation deps.media
    implementation deps.kotlinLib
    implementation deps.ktxCore
    implementation deps.rx3Android
    implementation deps.wpmzSdk
    implementation deps.rx3Kt
    implementation deps.lottie
    implementation deps.cardview
    implementation deps.mikepenzCommunityMaterial
    implementation deps.mikepenzGoogleMaterial
    implementation deps.mikepenzIconicsViews
    implementation deps.mikepenzIconicsCore
    implementation deps.mikepenzIonicons
    implementation deps.material

    api deps.maplibreAnotation
    api deps.maplibreTurf
    api deps.maplibreSdk
    api deps.amap3DMap
    api deps.amapSearch

    api deps.playservicesplaces
    api deps.playservicesmaps
    api deps.playserviceslocation
    api deps.playservicesbase

    compileOnly deps.aircraftProvided
    compileOnly deps.aircraft

}

```

Hope you can help me with this.

FYI, I have the same error when I try to run the [empty project with MSDK integrated] (https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/SDKSample.zip)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99862'>Zendesk ticket #99862</a>:<br><br>The 5.2.0 version has not been adapted for Android 13 yet. However, you can try updating to the 5.8.0 version. I have reviewed the information you provided, but I couldn't find any errors.
<br><p><em><small>°°°</small></em></p>

**Comment by HadrienBd** [comment]
I'm sorry for the missing context, I tried with 5.8 and then 5.2 but the result was the same. And as I said it also didn't work with the project with MSDK integrated.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99862'>Zendesk ticket #99862</a>:<br><br>Could you please try delaying the call to the 'init' interface by 3 to 5 seconds before executing it? Alternatively, you can force the execution of 'SDKManager.getInstance().init' on the main thread to see if it still crashes.
<br><p><em><small>°°°</small></em></p>

**Comment by HadrienBd** [comment]
Delaying didn't seems to do the trick but forcing the execution on the main thread did get me to onRegisterSuccess with no crash so I'm guessing it's working. Won't this have any impact on the sdk usage ? Can I use it safely as a solution ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99862'>Zendesk ticket #99862</a>:<br><br>Switching to the main thread will not affect the usage of the SDK. You can consider it as a solution.
<br><p><em><small>°°°</small></em></p>

**Comment by HadrienBd** [comment]
Great, thanks !

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99862'>Zendesk ticket #99862</a>:<br><br>Glad to help you!
<br><p><em><small>°°°</small></em></p>
