### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class dji.v5.manager.SDKManager

### ISSUE THREAD

**Issue by fail572872916** [dji-sdk/Mobile-SDK-Android-V5#280]
Process: com.suntoon.suntoonfly_v2, PID: 3251
                                                                                                    java.lang.VerifyError: Verifier rejected class dji.v5.manager.SDKManager: void dji.v5.manager.SDKManager.<init>() failed to verify: void dji.v5.manager.SDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor
                                                                                                     void dji.v5.manager.SDKManager.<init>(dji.v5.manager.SDKManager$1) failed to verify: void dji.v5.manager.SDKManager.<init>(dji.v5.manager.SDKManager$1): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.v5.manager.SDKManager' appears in /data/app/com.suntoon.suntoonfly_v2-24bVER68tWENx8hxxDoVcA==/base.apk!classes34.dex)
                                                                                                    	at dji.v5.manager.SDKManager.getInstance(Unknown Source:0)
                                                                                                    	at com.suntoon.suntoonfly_v2.viewmodel.MSDKManagerVM.initMobileSDK(MSDKManagerVM.kt:21)
                                                                                                    	at com.suntoon.suntoonfly_v2.DJIApplication.onCreate(DJIApplication.kt:23)
                                                                                                    	at com.suntoon.suntoonfly_v2.DJIAircraftApplication.onCreate(DJIAircraftApplication.kt:32)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6036)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:207)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6840)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101888'>Zendesk ticket #101888</a>:<br><br>Greetings!
Please try switching the logic of initializing the SDK and requesting registration to be executed on the main thread to see if the same crash issue still occurs.
Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
Still not working
![微信截图_20240304174825](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/02105b03-86ad-495b-95fb-bb437c4f6ab2)
![QQ截图20240304174625](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/aad04c41-2fcd-4862-862a-f3a43d5bff88)
![微信截图_20240304174646](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/9db15a2e-1d12-4a23-b39a-dd4e4cd5f459)

**Comment by fail572872916** [comment]
Upgraded from version 5.7.1

**Comment by dji-lyt** [comment]
Could you confirm if your app had no issues in version 5.7.1? Did you make a call to com.secneo.sdk.Helper.install(this)? For specific details on the call, please click on the link provided：https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-sample/src/main/java/dji/sampleV5/aircraft/DJIAircraftApplication.kt#L17

**Comment by fail572872916** [comment]
The reason is that I migrated uxsdk through viewbinding, and now I have re established the program from the official tutorial, and it is working properly. But I haven't restored the program I wrote before, so there must have been an issue during the migration process.

**Comment by fail572872916** [comment]
I will close this issue after I restore the previous program

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101888'>Zendesk ticket #101888</a>:<br><br>I will wait for your reply.
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
I haven't been able to fix the issue yet, but I did spend a long time rebuilding my project, ‘kotlin-android-extensions’ deprecated , and hopefully this will be removed in a future release

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101888'>Zendesk ticket #101888</a>:<br><br>I will provide your feedback to the team. I apologize for any inconvenience caused to you.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev @fail572872916 Any update for this issue?

**Comment by fail572872916** [comment]
> @dji-dev @fail572872916 Any update for this issue?这个问题有什么更新吗？
Problems with migrating to viewbiding on its own
