### ISSUE TITLE
ClassNotFoundException: Didn't find class "dji.v5.manager.interfaces.SDKManagerCallback"

### ISSUE THREAD

**Issue by Mulham6** [dji-sdk/Mobile-SDK-Android-V5#309]
Hi, I'm getting this runtime error when running [the empty sample app](https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/SDKSample.zip) on my Samsung A21s with Android 12:

`FATAL EXCEPTION: main
Process: com.example.msdksample, PID: 15696
java.lang.NoClassDefFoundError: Failed resolution of: Ldji/v5/manager/interfaces/SDKManagerCallback;
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
at android.app.LoadedApk.makeApplication(LoadedApk.java:1457)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
at android.app.ActivityThread.access$1600(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.v5.manager.interfaces.SDKManagerCallback" on path: DexPathList[[zip file "/data/app/~~QsPz8YOvtm3uPyXDHaYQCA==/com.example.msdksample-jsVwZkJqvhiqvRfa3x8yjA==/base.apk"],nativeLibraryDirectories=[/data/app/~~QsPz8YOvtm3uPyXDHaYQCA==/com.example.msdksample-jsVwZkJqvhiqvRfa3x8yjA==/lib/arm64, /data/app/~~QsPz8YOvtm3uPyXDHaYQCA==/com.example.msdksample-jsVwZkJqvhiqvRfa3x8yjA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

I'm using Android Studio Giraffe 2022.3.1 Patch 1 and get the same error on both Windows and Linux.
I tried delaying the call to the 'init' interface by 5 seconds before executing it and tried forcing the execution of 'SDKManager.getInstance().init' on the main thread. Both didn't seem to help.

It's registering successfully when running the exact same app on Nvidia ShieldTV pro with Android 11.

I'm not sure what I'm doing wrong. I really hope someone can help me out with this issue.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104656'>Zendesk ticket #104656</a>:<br><br>I can successfully initialize by running blank directly. If this is caused by a logic error in the code, it should occur on multiple devices.
Have you tried delaying for a longer period of time?
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
Using Handler().postDelayed I tried a whole two minutes delay and still got the same error.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104656'>Zendesk ticket #104656</a>:<br><br>Could you please run the sample code of MSDK on the device where this crash occurs? Will the sample code also experience the same crash?
https://github.com/dji-sdk/Mobile-SDK-Android-V5

The crash you are currently experiencing indicates that the program cannot find SDKManager. If the sample code also encounters the same crash, there may be compatibility issues with the SDK.
<br><p><em><small>°°°</small></em></p>

**Comment by danekpilar01** [comment]
Had the same issue, tried to call the `SDKManager.getInstance.init()` method in the ActivityClass (in onCreate method), not in the Application class, as they told us to do so in the tutorial, and it worked. Try it and see if it helps. Also try to run the method on the main thread (using getMainLooper for example).

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104656'>Zendesk ticket #104656</a>:<br><br>The purpose of switching the main thread and moving interface calls to the Activity should be to place the interface calls after the decryption of the SDK. The role of `com.secneo.sdk.Helper.install` is to trigger the decryption of the SDK, and before the decryption is completed, the SDK interfaces cannot be used properly.
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
I called `SDKManager.getInstance.init()` in the onCreate method of MainActivity class and it worked! Even without forcing a delay or execution on main thread.
Thanks a lot for the help!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104656'>Zendesk ticket #104656</a>:<br><br>I'm glad to hear that your issue has been resolved.
<br><p><em><small>°°°</small></em></p>
