### ISSUE TITLE
MSDK not working on API < 29 or x86

### ISSUE THREAD

**Issue by punto338** [dji-sdk/Mobile-SDK-Android-V5#331]
I am trying to run MSDK-V5 on my Android device API 29 but this error appears. It's working on my other device API 34 , I think its a arm64-v8a / armeabi-v7a issue. So does this mean that despite of minimum SDK is API 23 if you try to install in a API 25-26-27-28 device whic is not arm64-v8a will crash?

`
                                                                                                    Process: com.myapp.app, PID: 13459
                                                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.myapp.app-cwU_4l5tzLAx4VrVnTHnOQ==/base.apk", dex file "InMemoryDexFile[cookie=[0, 2805621280]]"],nativeLibraryDirectories=[/data/app/com.myapp.app-cwU_4l5tzLAx4VrVnTHnOQ==/lib/arm, /data/app/com.myapp.app-cwU_4l5tzLAx4VrVnTHnOQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libconstants.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1669)
                                                                                                    	at dji.v5.utils.inner.ConstantsUtils.<clinit>(ConstantsUtils.java:3)
                                                                                                    	at dji.v5.utils.inner.ConstantsUtils.co_c(ConstantsUtils.java:1)
                                                                                                    	at dji.v5.utils.inner.HttpsUtils.<clinit>(HttpsUtils.java:5)
                                                                                                    	at dji.v5.utils.inner.HttpsUtils.getDJISSLSocketFactoryForJavax(Unknown Source:0)
                                                                                                    	at dji.v5.network.OkHttpManager.<init>(SourceFile:5)
                                                                                                    	at dji.v5.network.OkHttpManager$Holder.<clinit>(SourceFile:3)
                                                                                                    	at dji.v5.network.OkHttpManager.getInstance(SourceFile:1)
                                                                                                    	at dji.v5.network.DJINetworkImp.<init>(SourceFile:24)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at dji.v5.manager.SDKManager.initDJINetworkManager(SDKManager.java:2)
                                                                                                    	at dji.v5.manager.SDKManager.co_a(SDKManager.java:14)
                                                                                                    	at dji.v5.manager.SDKManager.access$lambda$0(Unknown Source:0)
                                                                                                    	at dji.v5.manager.SDKManager$$Lambda$2.run(Unknown Source:6)`

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/8ff2fd0a-5399-4941-8321-250b138bda3b)
MSDK V5 is not compatible with armeabi-v7a.
