### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Needrom** [dji-sdk/Mobile-SDK-Android-V5#34]
### Problem
    ```
2022-09-02 09:47:32.855 11586-11586/com.dji.myapplication E/libc: Access denied finding property "ro.odm.prev.product.name"
2022-09-02 09:47:32.903 11586-11586/com.dji.myapplication E/Perf:  perftest packageName : com.dji.myapplication App is allowed to use Hide APIs  
2022-09-02 09:47:33.093 11586-11613/com.dji.myapplication E/libEGL: Invalid file path for libcolorx-loader.so
2022-09-02 09:47:33.235 11586-11586/com.dji.myapplication E/OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
2022-09-02 09:47:33.286 11586-11586/com.dji.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dji.myapplication, PID: 11586
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/aspectj/runtime/reflect/Factory;
        at dji.v5.manager.SDKManager.co_a(SDKManager.java:1)
        at dji.v5.manager.SDKManager.<clinit>(SDKManager.java:1)
        at dji.v5.manager.SDKManager.getInstance(SDKManager.java:1)
        at com.dji.myapplication.MainActivity.J(:24)
        at com.dji.myapplication.MainActivity.onCreate(:20)
        at android.app.Activity.performCreate(Activity.java:8153)
        at android.app.Activity.performCreate(Activity.java:8137)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3698)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3896)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2326)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8296)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.aspectj.runtime.reflect.Factory" on path: DexPathList[[zip file "/data/app/~~pbIfVAeDF_HZ0L7Ra3GJzg==/com.dji.myapplication-qpH91B55qUn1BNnozgRmUA==/base.apk", dex file "InMemoryDexFile[cookie=[0, 534337731008]]"],nativeLibraryDirectories=[/data/app/~~pbIfVAeDF_HZ0L7Ra3GJzg==/com.dji.myapplication-qpH91B55qUn1BNnozgRmUA==/lib/arm64, /data/app/~~pbIfVAeDF_HZ0L7Ra3GJzg==/com.dji.myapplication-qpH91B55qUn1BNnozgRmUA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ```

### Device 
- OPPO K5

### Android API
- Android 29 

###  Gradle Version
- Android Gradle Plugin Version: 4.2.2
- Gradle Version 7.3.3

**Comment by DJI-William** [comment]
Is our MSDK V5 Sample instantly crashed when open it on OPPO K5?

**Comment by Needrom** [comment]
> Is our MSDK V5 Sample instantly crashed when open it on OPPO K5?

Nope, this is the developer tutorial result which I forgot to add the proguard-rules.Already fixed now.
