### ISSUE TITLE
Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE

### ISSUE THREAD

**Issue by namnhbhtech** [dji-sdk/Mobile-SDK-Android-V5#370]
Steps to reproduce:
1. update android target sdk version
2. migrate methods if needs
3. build then open app on device android 14
4. plugging controller usb when app is running

gradle.properties
```
#build config
ANDROID_MIN_SDK_VERSION=26
ANDROID_TARGET_SDK_VERSION=34
ANDROID_COMPILE_SDK_VERSION=34
```

```
FATAL EXCEPTION: dji_background_thread (Ask Gemini)
Process: com.dji.sampleV5.aircraft, PID: 24822
java.lang.IllegalArgumentException: com.dji.sampleV5.aircraft: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3073)
at android.os.Parcel.createException(Parcel.java:3053)
at android.os.Parcel.readException(Parcel.java:3036)
at android.os.Parcel.readException(Parcel.java:2978)
at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7027)
at java.lang.reflect.Method.invoke(Native Method)
at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy3.getIntentSenderWithFeature(Unknown Source)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:752)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:735)
at dji.sdk.datalink.usb.co_a.co_a(DJIUsbAccessoryReceiver.java:280)
at dji.sdk.datalink.usb.co_a.co_i(DJIUsbAccessoryReceiver.java:5)
at dji.sdk.datalink.usb.co_a$co_b.handleMessage(DJIUsbAccessoryReceiver.java:3)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:6468)
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:6411)
at android.app.IActivityManager$Stub.onTransact$getIntentSenderWithFeature$(IActivityManager.java:11885)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3375)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3198)
```
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/130335226/80408de9-4bbc-4ecb-84e6-3b0d31654556)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109722'>Zendesk ticket #109722</a>:<br><br>The Mobile SDK has not been adapted for Android 14 yet, so the TargetSDKversion cannot be set to 34.
<br><p><em><small>°°°</small></em></p>

**Comment by psino-skg** [comment]
Hi,
this error still occurs with MSDK V5.10.0 and controller DJI RC231.

Gradle settings:
Android Min SDK: 26
Android Target SDK: 34
Android Compile SDK: 34

With target SDK 33 is everything working fine, but SDK 33 is not acceptable for apps to be submitted to Google Play.
[https://developer.android.com/google/play/requirements/target-sdk](url)

> Starting August 31 2024:
> New apps and app updates must target Android 14 (API level 34) or higher to be submitted to Google Play; except for Wear OS and Android TV apps, which must target Android 13 (API level 33) or higher.

**Comment by dji-lyt** [comment]
The beta version for Android 14 has released:https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha
