### ISSUE TITLE
Getting crash in Android  9 (Pie)

### ISSUE THREAD

**Issue by utsavclearspot** [dji-sdk/Mobile-SDK-Android-V5#398]
Here is the crash logs
`FATAL EXCEPTION: DJIExecutor IO #1
                                                                                                    Process: com.dji.sampleV5.aircraft, PID: 5736
                                                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dji.sampleV5.aircraft-dHvO8y6--G4inSwzjYvyoA==/base.apk"],nativeLibraryDirectories=[/data/app/com.dji.sampleV5.aircraft-dHvO8y6--G4inSwzjYvyoA==/lib/arm, /data/app/com.dji.sampleV5.aircraft-dHvO8y6--G4inSwzjYvyoA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libconstants.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1669)
                                                                                                    	at dji.v5.utils.inner.ConstantsUtils.<clinit>(ConstantsUtils.java:3)
                                                                                                    	at dji.v5.utils.inner.ConstantsUtils.co_c(ConstantsUtils.java:1)
                                                                                                    	at dji.v5.utils.inner.HttpsUtils.<clinit>(HttpsUtils.java:5)
                                                                                                    	at dji.v5.utils.inner.HttpsUtils.getDJISSLSocketFactoryForJavax(HttpsUtils.java:1)
                                                                                                    	at dji.v5.network.OkHttpManager.<init>(OkHttpManager.java:9)
                                                                                                    	at dji.v5.network.OkHttpManager$Holder.<clinit>(OkHttpManager.java:2)
                                                                                                    	at dji.v5.network.OkHttpManager.getInstance(OkHttpManager.java:1)
                                                                                                    	at dji.v5.network.DJINetworkImp.<init>(DJINetworkImp.java:10)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at dji.v5.manager.SDKManager.initDJINetworkManager(SDKManager.java:2)
                                                                                                    	at dji.v5.manager.SDKManager.co_a(SDKManager.java:14)
                                                                                                    	at dji.v5.manager.SDKManager.lambda$qQ8vfHm0Pi84vcg6DvVpTrMbJgY(Unknown Source:0)
                                                                                                    	at dji.v5.manager.-$$Lambda$SDKManager$qQ8vfHm0Pi84vcg6DvVpTrMbJgY.run(Unknown Source:6)`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/114254'>Zendesk ticket #114254</a>:<br><br>MSDK V5 currently does not support the armeabi-v7a architecture. Is your device only compatible with armeabi-v7a?
<br><p><em><small>°°°</small></em></p>
