### ISSUE TITLE
Unreliable DJI registration (COULD_NOT_CONNECT_TO_INTERNET) despite good internet connection

### ISSUE THREAD

**Issue by petered** [dji-sdk/Mobile-SDK-Android-V5#433]
I'm on an RC-Pro controller here, running the DJI 5 SDK, with the Sample app.
Whenever I uninstall / reinstall the app, I need to register the DJI SDK.
The problem is that registration is very unreliable.

I'll often get the message 
```
COULD_NOT_CONNECT_TO_INTERNET: Registration Failed - For first time registration, app should be connected to Internet.
```
See picture at bottom. 

Things I have checked:
* The internet works.  I can look up anything and get quick response with the Firefox web-browser on the RC-Pro.
* Just in case I've tried switching to my mobile hotspot.  It still fails.
* Yes I've [registered with DJI developer](https://developer.dji.com/user/apps/#all), and yes the `application_id` matches the package name in the registration.  I know it _can_ work because registration has succeeded before with the exact same code.  
* No other apps are running.  I've even "Force Quit" DJI Fly - which I know can interfere with the sample app.

If I keep restarting, it eventually **does** register - though sometimes I have to try again hours later.  This leads me to think it's a DJI server issue, but I'm not sure.  

When I get the registration failure, I'll typically see a message like the one below in logcat:

```
2024-10-16 15:43:54.034  9776-9840  KeyStore                com.dji.sampleV5.aircraft            W  KeyStore exception
                                                                                                    android.os.ServiceSpecificException:  (code 7)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2085)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2039)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1987)
                                                                                                    	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:978)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:236)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:225)
                                                                                                    	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
                                                                                                    	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
                                                                                                    	at android.security.net.config.KeyStoreCertificateSource.ensureInitialized(KeyStoreCertificateSource.java:61)
                                                                                                    	at android.security.net.config.KeyStoreCertificateSource.findBySubjectAndPublicKey(KeyStoreCertificateSource.java:77)
                                                                                                    	at android.security.net.config.CertificatesEntryRef.findBySubjectAndPublicKey(CertificatesEntryRef.java:47)
                                                                                                    	at android.security.net.config.NetworkSecurityConfig.findTrustAnchorBySubjectAndPublicKey(NetworkSecurityConfig.java:123)
                                                                                                    	at android.security.net.config.TrustedCertificateStoreAdapter.getTrustAnchor(TrustedCertificateStoreAdapter.java:51)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:964)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
                                                                                                    	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                                                    	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
                                                                                                    	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
                                                                                                    	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
                                                                                                    	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                                                    	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
                                                                                                    	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
                                                                                                    	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
                                                                                                    	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
                                                                                                    	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
                                                                                                    	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                                                                                                    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
                                                                                                    	at okhttp3.RealCall.execute(RealCall.java:81)
                                                                                                    	at dji.v5.network.DJINetworkImp.execute(DJINetworkImp.java:15)
                                                                                                    	at dji.v5.network.DJINetworkManager.execute(DJINetworkManager.java:1)
2024-10-16 15:43:54.034  9776-9840  KeyStore                com.dji.sampleV5.aircraft            W  	at dji.v5.inner.register.RegistrationManager.co_b(RegistrationManager.java:7)
                                                                                                    	at dji.v5.inner.register.RegistrationManager.co_d(RegistrationManager.java:6)
                                                                                                    	at dji.v5.inner.register.RegistrationManager.co_a(RegistrationManager.java:25)
                                                                                                    	at dji.v5.manager.SDKManager.co_d(SDKManager.java:29)
                                                                                                    	at dji.v5.manager.-$$Lambda$bhS6CzRbuqifwi9hiPaPQVKJllY.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
2024-10-16 15:43:55.170  9776-9813  LeakCanary              com.dji.sampleV5.aircraft            D  Setting up flushing for Thread[LeakCanary-Heap-Dump,5,main]
2024-10-16 15:43:55.173  9776-9813  LeakCanary              com.dji.sampleV5.aircraft            D  Setting up flushing for Thread[AnalyticsEngineCallBack_Handler,5,main]
2024-10-16 15:43:55.174  9776-9813  LeakCanary              com.dji.sampleV5.aircraft            D  Setting up flushing for Thread[LogHandlerThread,3,main]
2024-10-16 15:43:55.174  9776-9813  LeakCanary              com.dji.sampleV5.aircraft            D  Setting up flushing for Thread[ConnectivityThread,3,main]
2024-10-16 15:44:04.054  9776-9840  http execute error      com.dji.sampleV5.aircraft            E  timeout 
2024-10-16 15:44:04.061  9776-9840  DjiSdk5Manager          com.dji.sampleV5.aircraft            I  Registration Failed - For first time registration, app should be connected to Internet.
```

![IMG_20241016_155239_7](https://github.com/user-attachments/assets/0c2ff95f-1f2a-4ddb-bb37-8c235df83e94)

---

Translation by ChatGPT. 请原谅任何错误。

我在这里使用的是RC-Pro控制器，运行的是DJI 5 SDK和Sample应用程序。
每次我卸载/重新安装应用程序时，我需要重新注册DJI SDK。
问题是，注册过程非常不稳定。

我经常收到以下信息：

```
COULD_NOT_CONNECT_TO_INTERNET: 注册失败 - 第一次注册时，应用程序应连接到互联网。
```
请参见底部的图片。

我已检查的事项：

* 互联网是正常的。我可以在RC-Pro上使用Firefox浏览器快速查找任何信息并得到响应。
* 以防万一，我也尝试了切换到我的手机热点，但仍然失败。
* 是的，我已经[在DJI开发者平台注册](https://developer.dji.com/user/apps/#all)，并且application_id与注册时的包名匹配。我知道它_可以_工作，因为之前相同的代码已成功注册。
* 没有其他应用程序在运行。我甚至强制停止了DJI Fly应用程序，因为我知道它会干扰Sample应用程序。
* 如果我继续重启，最终它确实会注册，尽管有时我必须等几个小时再试。这让我认为可能是DJI服务器的问题，但我不确定。

当我遇到注册失败时，通常会在logcat中看到类似下面的信息：

**Comment by petered** [comment]
So - just 10 minutes after creating this issue - the app registered successfully.  

Then I uninstalled it and reinstalled it, and I get the same `COULD_NOT_CONNECT_TO_INTERNET` error, despite having a good connection.

After restarting my Wifi connection - it registers reliably now.  So it may have been some issue with the internet connection - even though the internet seemed to work from the browser.   

I'll close this issue for now.  If someone runs into the same problem - try turning your wifi connection off and on again!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/119617'>Zendesk ticket #119617</a>:<br><br>Thank you for sharing your case; it will help many others, including us.
<br><p><em><small>°°°</small></em></p>
