### ISSUE TITLE
SDK error

### ISSUE THREAD

**Issue by Chen-Zhihui** [dji-sdk/Mobile-SDK-Android-V5#458]
java.lang.VerifyError: Verifier rejected class dji.v5.utils.common.LogUtils: void dji.v5.utils.common.LogUtils.<init>() failed to verify: void dji.v5.utils.common.LogUtils.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.v5.utils.common.LogUtils' appears in /data/app/~~C0mXWbnAvZb58BninRmZNQ==/s.hou-xMMHBH7rSxVZKRIM-fuLhw==/base.apk!classes8.dex)
                                                                                                    	at dji.v5.utils.common.LogUtils.getTag(Unknown Source:0)
                                                                                                    	at s.chihou.HouMainActivity.<init>(HouMainActivity.kt:37)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:44)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124509'>Zendesk ticket #124509</a>:<br><br>Dear developer,
Hello, thank you for contacting DJI Innovations.

May I ask what your usage scenario is and can you provide a replication path?

Thank you for your email. Wishing you a happy life!
Best Regards,
DJI Innovation SDK Technical Support
<br><p><em><small>°°°</small></em></p>

**Comment by Chamud** [comment]
Can I know how you fixed it?
