### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by gg-deploy-dd** [dji-sdk/Mobile-SDK-Android-V5#67]
Saw an instance of the following exception

java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at dji.v5.manager.aircraft.rtk.RTKCenter.co_a(RTKCenter.java:23)
    at dji.v5.manager.aircraft.rtk.RTKCenter.co_a(RTKCenter.java:11)
    at dji.v5.manager.aircraft.rtk.RTKCenter.access$lambda$3
    at dji.v5.manager.aircraft.rtk.RTKCenter$$Lambda$4.onValueChange
    at dji.v5.common.utils.CallbackUtils.onValueChange(CallbackUtils.java:1)
    at dji.v5.manager.KeyManager.co_a(KeyManager.java:1)
    at dji.v5.manager.KeyManager.access$lambda$0
    at dji.v5.manager.KeyManager$$Lambda$1.co_a
    at dji.sdk.keyvalue.push.co_b.co_a(PushRecorder.java:60)
    at dji.sdk.keyvalue.push.co_b.co_a(PushRecorder.java:50)
    at dji.sdk.keyvalue.push.co_b.access$lambda$1
    at dji.sdk.keyvalue.push.co_b$$Lambda$2.run

**Comment by DJI-William** [comment]
1. What is your aircraft model?
2. What is your MSDK version?
3. How to reproduce it?

**Comment by gg-deploy-dd** [comment]
Hello William,
Aircraft model - M3E
MSDK - 5.2.0
We dont know the exact steps that lead to this exception being thrown.

**Comment by DJI-William** [comment]
Fixed, 5.3.0 is about to released in earily April.
