### ISSUE TITLE
DJI 5 SDK crash after attaching a drone controller via USB

### ISSUE THREAD

**Issue by neilyoung** [dji-sdk/Mobile-SDK-Android-V5#77]
Your sample app from here https://developer.dji.com/doc/mobile-sdk-tutorial/en/quick-start/user-project-caution.html was run on a  DJI M300 smart controller and an Android 13 smartphone (that was reported to me, not my own experience). 

Note: The sample app did not contain UXSDK.

This is the crash dump. 

` Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

Mimimum SDK is 24
Target and Build SDK 33

```
2023-02-22 17:01:34.200 15982-16039/? I/myApp: myApp onRegisterSuccess
2023-02-22 17:01:34.200 15982-15982/? D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 11342; state: ENABLED
2023-02-22 17:01:34.203 15982-15982/? V/Toast: show: caller = com.dji.myapplication.MainActivity$registerApp$1.onRegisterSuccess$lambda$0:54 
2023-02-22 17:01:34.203 15982-15982/? V/Toast: show: isFocusInDesktop = false mCustomDisplayId = -1 isDexDualMode = false isActivityContext = true
2023-02-22 17:01:34.208 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.209 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.224 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.224 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.225 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.226 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.226 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.226 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.227 15982-16070/? I/DJIV5/LTEService@2a17cdd: (co_b:3) set failure： false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.227 15982-16071/? I/DJIV5/LTEService@2a17cdd: (co_a:106) set failure： false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.548 15982-16060/? I/DJIV5/co_a@284409d: (onCompleted:1) load cloud config complete {"a":{"control_lte":{"a":"control_lte","b":{"area_config_whitelist":{"a":"area_config_whitelist","b":"{\"lte_feature_support_country_code\":[\"CN\"],\"sdr_lost_block_motor_before_takeoff_country_code\":[\"CN\"],\"sdr_lost_block_motor_land_over_3min_country_code\":[\"CN\"]}"},"area_config_whitelist_v5_kol":{"a":"area_config_whitelist_v5_kol","b":"{\"lte_feature_support_country_code\":[\"CN\",\"AR\",\"CL\",\"PT\",\"FR\",\"GR\",\"DE\",\"IT\",\"SE\",\"TR\",\"NO\",\"CH\",\"SG\",\"AU\",\"NZ\",\"MY\",\"JP\"],\"sdr_lost_block_motor_before_takeoff_country_code\":[\"CN\"],\"sdr_lost_block_motor_land_over_3min_country_code\":[\"CN\"]}"}}}}} 
2023-02-22 17:01:34.548 15982-16060/? I/DJIV5/co_a@284409d: (co_a:40) entry.getStringValue() {"lte_feature_support_country_code":["CN"],"sdr_lost_block_motor_before_takeoff_country_code":["CN"],"sdr_lost_block_motor_land_over_3min_country_code":["CN"]} 
2023-02-22 17:01:34.549 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.550 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.550 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.550 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.551 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.551 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.552 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventNeverTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.552 15982-15982/? E/DJIV5/RXUtil: (onFailure:1) SdrLostPreventHasTakeoffEnable-onFailure false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.552 15982-16074/? I/DJIV5/LTEService@2a17cdd: (co_a:106) set failure： false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:34.552 15982-16061/? I/DJIV5/LTEService@2a17cdd: (co_b:3) set failure： false ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'} 
2023-02-22 17:01:35.900 15982-16057/? D/CompatibilityChangeReporter: Compat change id reported: 160794467; UID 11342; state: ENABLED
2023-02-22 17:01:35.901 15982-16057/? E/AndroidRuntime: FATAL EXCEPTION: dji_background_thread
    Process: com.dji.myapplication, PID: 15982
    java.lang.IllegalArgumentException: com.dji.myapplication: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:688)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:675)
        at dji.sdk.datalink.usb.co_a.co_a(DJIUsbAccessoryReceiver.java:36)
        at dji.sdk.datalink.usb.co_a.co_i(DJIUsbAccessoryReceiver.java:5)
        at dji.sdk.datalink.usb.co_a.co_d(DJIUsbAccessoryReceiver.java:1)
        at dji.sdk.datalink.usb.co_a$co_b.handleMessage(DJIUsbAccessoryReceiver.java:2)
        at android.os.Handler.dispatchMessage(Handler.java:102)
2023-02-22 17:01:35.908 15982-16057/? E/DJIV5/Class@e5726a7: (co_b:42) Stream closed 
2023-02-22 17:01:35.916 15982-16057/? E/DJIV5/Class@e5726a7: (co_c:40) build 
2023-02-22 17:01:35.916 15982-16057/? E/DJIV5/SDKConfig: (getPackageProductCategory:10) dji.v5.handheld.BuildConfig 
2023-02-22 17:01:35.921 15982-16061/? E/DJIV5/RXUtil: (co_a:27) io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.rxjava3.exceptions.MissingBackpressureException: Can't deliver value due to lack of requests 
2023-02-22 17:01:38.985 15982-15982/? I/ViewRootImpl@cc67f52[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 0
2023-02-22 17:01:39.002 15982-15982/? V/ViewRootImpl@cc67f52[MainActivity]: updateAppliedLetterboxDirection, direction=0, Caller=android.view.ViewRootImpl.handleDispatchLetterboxDirectionChanged:13406

```

**Comment by DJI-William** [comment]
We havn't support 33 yet. I remember the Sample supports up to 29. Please downgrade the Android SDK and try again. minSDKVersion also matters. I have already created a story ticket to support 33 in the story backlog.

**Comment by neilyoung** [comment]
OK, I can do this. Note, your sample supports 32. And the error message talks about "version 31 and above". I can do this, but I have not much hope.

**Comment by neilyoung** [comment]
Now: 32 or 31?

**Comment by DJI-William** [comment]
Sorry, sample is using
ANDROID_MIN_SDK_VERSION=21
ANDROID_TARGET_SDK_VERSION=29
ANDROID_COMPILE_SDK_VERSION=29

**Comment by neilyoung** [comment]
You mean the full sample? I was talking about your quick start (see first post here).

With 29 you cannot even land in the Google app store anymore.

**Comment by DJI-William** [comment]
https://stackoverflow.com/questions/69783824/targeting-s-version-31-and-above-requires-that-one-of-flag-immutable-or-flag
There are some possbile answers on Google. I think it is not the Android version issue. Becareful with the Androidx version. I use 
implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'

    //MSDK V5
    implementation 'com.dji:dji-sdk-v5-aircraft:5.2.0'
    runtimeOnly 'com.dji:dji-sdk-v5-networkImp:5.2.0'
    compileOnly 'com.dji:dji-sdk-v5-aircraft-provided:5.2.0'

    //三方依赖库
    implementation 'com.squareup.okio:okio:1.15.0'
    implementation 'com.squareup.wire:wire-runtime:2.2.0'
    implementation 'com.airbnb.android:lottie:3.3.1'

**Comment by neilyoung** [comment]
The project created from scratch with AS Electric Eel  uses this:

```
// Not used
// implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
implementation 'androidx.core:core-ktx:1.7.0'
implementation 'androidx.appcompat:appcompat:1.6.1'
implementation 'com.google.android.material:material:1.8.0'
implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
testImplementation 'junit:junit:4.13.2'
androidTestImplementation 'androidx.test.ext:junit:1.1.5'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'
```

So some versions a bit upgraded. MSDK 5 as above.

I also have to say, that the app on an Android 12 (level 32) works. So I suppose the combination of target/compile 33 and an Android 13 is problematic for DJI. 

How could you just mess it up that badly?

**Comment by neilyoung** [comment]
The app does not crash if downgrading to SDK 30, min 23. And after downgrading some dependencies (as you described).

So again - your product is not fit for the present.

But I'm having a question:

After having received "Product connected" - shouldn't these calls give me something more than just NULL (ignore the strange naming):

```
val z = VideoStreamManager().availableStreamSources
val q = VideoStreamManager().availableVideoChannels
val x = VideoStreamManager().getAvailableVideoChannels(VideoChannelType.PRIMARY_STREAM_CHANNEL)
```

I was hoping this, but the result on two different devices is:

```
2023-02-23 11:49:18.086 2397-2397/com.dji.myapplication I/myApp: X:null, Z:null, Q: null
```

I'm just asking, because this source https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/video-stream.html says, this would be the question to be asked first.

**Comment by neilyoung** [comment]
Other than that: Think about ways to give me Remote Access to a system (maybe a VM running Ubuntu 20.04, having Android Studio installed and Wifi access to an Android device and USB access to a drone and all this powered 24/7)

Then we don't need this "Test this apk" steps and we probably also don't need to rent expensive things.

**Comment by DJI-William** [comment]
It depends on when you called this. Obviously you are calling these method before the camera is ready. At least the ProductKey.KeyConnection and the CameraKey.KeyConnection needs to be come true.

**Comment by neilyoung** [comment]
Ok. Thanks. Where is this documented and how can I obtain this info?

**Comment by DJI-William** [comment]
You can find the [DJIKey](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/DJIKey.html) and its [tutorial](https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/keymanager.html).

**Comment by neilyoung** [comment]
I don't get it. What kind of documentation is that? Why not simply sample code?

**Comment by neilyoung** [comment]
Would you mind to provide a two liner in order to get these two things?

**Comment by DJI-William** [comment]
Please look at the sample, you need to called getInstance.
![image](https://user-images.githubusercontent.com/77274755/221161229-70867730-3489-49f9-a559-c0ee6fdf66d7.png)
